# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable-kf6'
    'frameworks/karchive': '@stable-kf6'
    'frameworks/kcompletion': '@stable-kf6'
    'frameworks/kconfig': '@stable-kf6'
    'frameworks/kconfigwidgets': '@stable-kf6'
    'frameworks/kcoreaddons': '@stable-kf6'
    'frameworks/kcrash': '@stable-kf6'
    'frameworks/kdbusaddons': '@stable-kf6'
    'frameworks/kdoctools': '@stable-kf6'
    'frameworks/ki18n': '@stable-kf6'
    'frameworks/kiconthemes': '@stable-kf6'
    'frameworks/kio': '@stable-kf6'
    'frameworks/ktextwidgets': '@stable-kf6'
    'frameworks/kxmlgui': '@stable-kf6'
    'frameworks/kwidgetsaddons': '@stable-kf6'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
