
#
# Yes, this is the Makefile you should use if you downloaded the
# source distribution.
#
# just type:
# make -f Makefile.dist
#

default: all

all:
	-rm -f config.h
	-rm -f config.cache
	-rm -f config.status
	aclocal
	autoheader
	automake
	autoconf
	./configure ${CONFIGURE_OPTS}
	# now you can run "make"
