# SPDX-FileCopyrightText: 2024-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kwave
confinement: strict
grade: stable
base: core24
adopt-info: kwave
apps:
  kwave:
    extensions:
      - kde-neon-6
    common-id: org.kde.kwave.desktop
    desktop: usr/share/applications/org.kde.kwave.desktop
    command: usr/bin/kwave
    plugs:
      - audio-record
      - home
environment:
  ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kwave
    bus: session
parts:
  kwave:
    parse-info:
      - usr/share/metainfo/org.kde.kwave.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libxml2-dev
      - gettext
      - doxygen
      - graphviz
      - libxml2-utils
      - docbook-xml
      - docbook-xsl
      - libaudiofile-dev
      - libsamplerate0-dev
      - libasound2-dev
      - libpulse-dev
      - libflac-dev
      - libflac++-dev
      - libid3-3.8.3-dev
      - libmad0-dev
      - libopus-dev
      - libvorbis-dev
      - libfftw3-dev
      - libpulse0
    stage-packages:
      - gstreamer1.0-alsa
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libasound2
      - libasound2-data
      - libasound2-plugins
      - libasound2-plugins-extra
      - libaudiofile1
      - libsamplerate0
      - libpulse0
      - libflac12t64
      - libflac++10
      - flac
      - libid3-tools
      - libmad0
      - libopus0
      - libvorbis0a
      - libfftw3-bin
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [kwave]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kwave
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
