#!/bin/sh
############################################################################
#        fix-common  -  fix the "common" directory of HTML help
#                            -------------------
#   begin                : Tue Jul 27 2004
#   copyright            : (C) 2004 by Thomas Eschenbacher
#   email                : Thomas.Eschenbacher@gmx.de
############################################################################
#
############################################################################
#                                                                          #
#    This program is free software; you can redistribute it and/or modify  #
#    it under the terms of the GNU General Public License as published by  #
#    the Free Software Foundation; either version 2 of the License, or     #
#    (at your option) any later version.                                   #
#                                                                          #
############################################################################

for file in *.html; do {
        cat $file \
            | sed s+help:/common+./common+g \
            | sed s+help:/kdoctools5-common+./common+g \
            > $file.new
        mv $file.new $file
} done

### EOF ###
