all:
	@echo "This file is to make it easier for you to create all you need"
	aclocal
	autoheader
# use --include-deps, if you want to release the stuff. Don't use it for
# yourself
	automake --include-deps
	autoconf
	touch stamp-h.in
	rm -r Makefile.dist # remove this file

