/* 
 * this file was automatically generated by menusconfig2cpp.sh 
 * at Sat May 20 16:31:15 CEST 2000 -> DO NOT EDIT ! 
 */

#include <kapp.h> // (for i18n macro) 

static void dummy(const char *string_to_be_internationalized) { }

static void internationalize_all()
{

    dummy(i18n("&8 Bit"));
    dummy(i18n("&About kwave..."));
    dummy(i18n("&Add"));
    dummy(i18n("&Additive Synthesis"));
    dummy(i18n("&All"));
    dummy(i18n("&Amplify"));
    dummy(i18n("&As..."));
    dummy(i18n("&Average spectrum"));
    dummy(i18n("&Blocks..."));
    dummy(i18n("&Calculate"));
    dummy(i18n("&Center Signal"));
    dummy(i18n("&Change rate"));
    dummy(i18n("&Choose type"));
    dummy(i18n("&Clipboard"));
    dummy(i18n("&Close"));
    dummy(i18n("&Contents"));
    dummy(i18n("&Convert label distance to pitch"));
    dummy(i18n("&Copy"));
    dummy(i18n("&Create"));
    dummy(i18n("&Crop"));
    dummy(i18n("&Delete"));
    dummy(i18n("&Distort"));
    dummy(i18n("&Edit"));
    dummy(i18n("&Enter Command"));
    dummy(i18n("&Envelope"));
    dummy(i18n("&Expand to labels"));
    dummy(i18n("&Export to Ascii..."));
    dummy(i18n("&File"));
    dummy(i18n("&Filter"));
    dummy(i18n("&Flip Phase"));
    dummy(i18n("&Flush"));
    dummy(i18n("&Free"));
    dummy(i18n("&Frequencies"));
    dummy(i18n("&Generate"));
    dummy(i18n("&Help"));
    dummy(i18n("&Import Ascii..."));
    dummy(i18n("&Insert labels..."));
    dummy(i18n("&Invert Selection"));
    dummy(i18n("&Labels"));
    dummy(i18n("&Load labels..."));
    dummy(i18n("&Memory"));
    dummy(i18n("&Menus"));
    dummy(i18n("&Mix"));
    dummy(i18n("&Mix & Paste"));
    dummy(i18n("&Moving Average"));
    dummy(i18n("&New &Window"));
    dummy(i18n("&New..."));
    dummy(i18n("&Next"));
    dummy(i18n("&Next Page"));
    dummy(i18n("&Noise"));
    dummy(i18n("&Nothing"));
    dummy(i18n("&Open"));
    dummy(i18n("&Open Recent"));
    dummy(i18n("&Options"));
    dummy(i18n("&Paste"));
    dummy(i18n("&Periodic Silence"));
    dummy(i18n("&Playback"));
    dummy(i18n("&Presets"));
    dummy(i18n("&Previous"));
    dummy(i18n("&Previous Page"));
    dummy(i18n("&Pulse Train"));
    dummy(i18n("&Quit"));
    dummy(i18n("&Range"));
    dummy(i18n("&Resample"));
    dummy(i18n("&Reverse"));
    dummy(i18n("&Revert"));
    dummy(i18n("&Save"));
    dummy(i18n("&Select all"));
    dummy(i18n("&Selection"));
    dummy(i18n("&Selection..."));
    dummy(i18n("&Silence"));
    dummy(i18n("&Sonagram"));
    dummy(i18n("&View"));
    dummy(i18n("&Visible area"));
    dummy(i18n("&to end"));
    dummy(i18n("&to new Window"));
    dummy(i18n("&to start"));
    dummy(i18n("1&6 Bit"));
    dummy(i18n("2&4 Bit"));
    dummy(i18n("C&hannel"));
    dummy(i18n("Create &type"));
    dummy(i18n("Cu&t"));
    dummy(i18n("De&lay"));
    dummy(i18n("F&x"));
    dummy(i18n("Fade &In"));
    dummy(i18n("Fade &Out"));
    dummy(i18n("Label by &Intensity"));
    dummy(i18n("Label by &Period"));
    dummy(i18n("Labels ..."));
    dummy(i18n("Periods ..."));
    dummy(i18n("Re&quantize"));
    dummy(i18n("S&ave"));
    dummy(i18n("Save &resolution"));
    dummy(i18n("Scroll &left"));
    dummy(i18n("Scroll &right"));
    dummy(i18n("Spe&ctrum"));
    dummy(i18n("Tri&m"));
    dummy(i18n("Zoom &In"));
    dummy(i18n("Zoom &Out"));
    dummy(i18n("Zoom to &Selection"));
    dummy(i18n("to &Maximum"));
    dummy(i18n("to be done..."));
    dummy(i18n("with &Clipboard"));
}

/* end of file */

